#pragma config(Sensor, S1,     touch,          sensorEV3_Touch)
#pragma config(Sensor, S2,     light,          sensorEV3_Color)
#pragma config(Sensor, S4,     sonarsensor,    sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define SIZE 100


void count_line(int count)
{
	//set counter to 0
	int counter=0;

	//while counter is less than count which is defined at the start 
	while(counter < count)
	{
		//goes straight 
		motor[motorC]=50;
		motor[motorB]=50;

		//detects the black line
		while(SensorValue(light)<=45)
		{
			//goes straight
			motor[motorC]=50;
			motor[motorB]=50;

			//display the number of lines
			displayCenteredBigTextLine(3, "%d", counter);
		}//end while inner
		
		//increment the counter to keep track
		counter++;

		//on the white space
		while(SensorValue(light)>=45)
		{
			//goes straight
			motor[motorC]=50;
			motor[motorB]=50;
			
			//display the number of lines
			displayCenteredBigTextLine(3, "%d", counter);
		}//end whille inner
	}//end while outter
}//end count_line function




task main()
{
	int count;
	count = SIZE;
	//call the function count_line
	count_line(count);
}//end main
