#pragma config(Sensor, S1,     touch,          sensorEV3_Touch)
#pragma config(Sensor, S2,     light,          sensorEV3_Color)
#pragma config(Sensor, S4,     sonarsensor,    sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard
void straight()
{
	int counter=0;

	while(counter <=3)
	{
			motor[motorC]=50;
			motor[motorB]=50;

			while(SensorValue(light)<=45)
			{
				motor[motorC]=50;
				motor[motorB]=50;

				displayCenteredBigTextLine(3, "%d", counter);
		}
		counter++;

		while(SensorValue(light)>=45)
		{
			motor[motorC]=50;
			motor[motorB]=50;

			displayCenteredBigTextLine(3, "%d", counter);
	}
}


}

task main()
{
	straight();
}
