#pragma config(Sensor, S2,     light,          sensorEV3_Color)
#pragma config(Sensor, S4,     sonarsensor,    sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1)
	{
		if(SensorValue(sonarSensor)<25)
		{
			motor[motorC]=0;
			motor[motorB]=20;
			wait1Msec(1000);

			motor[motorC]=25;
			motor[motorB]=25;
			wait1Msec(1500);

			motor[motorC]=20;
			motor[motorB]=0;
			wait1Msec(1000);

			motor[motorC]=25;
			motor[motorB]=25;
			wait1Msec(1500);

			motor[motorC]=20;
			motor[motorB]=0;
			wait1Msec(1000);

			motor[motorC]=20;
			motor[motorB]=20;
			wait1Msec(2000);

			motor[motorC]=0;
			motor[motorB]=20;
			wait1Msec(1000);

			motor[motorC]=0;
			motor[motorB]=20;
			wait1Msec(1000);
		}

		while(SensorValue(light)<45)
		{
			motor[motorC]=0;
			motor[motorB]=20;
		}
		while(SensorValue(light)>=45)
		{
			motor[motorC]=20;
			motor[motorB]=0;
		}
}




}
