#pragma config(Sensor, S1,     touch,          sensorEV3_Touch)
#pragma config(Sensor, S2,     light,          sensorEV3_Color)
#pragma config(Sensor, S4,     sonarsensor,    sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard
void TurnRight()
{
	motor[motorC]=50;
	motor[motorB]=0;
	sleep(700);
}
task main()
{
	TurnRight();
}
